platform :ios, '14.0'
use_frameworks!

def portals_pods
  pod 'Capacitor'
  pod 'IonicPortals', :git => 'https://github.com/ionic-team/ionic-portals-ios.git', :branch => 'main'
  pod "CapacitorCamera"
end

target 'Ecommerce' do
  portals_pods
end

target 'EcommerceLiveUpdates' do
  portals_pods
end

target 'EcommerceTests' do
  portals_pods
end
