source 'https://github.com/native-portal/podspecs.git'

platform :ios, '12.0'
use_frameworks!

def portals_pods
    pod 'Capacitor'
    pod 'IonicPortals'
    pod "CapacitorCamera"
end

target 'Ecommerce' do
  portals_pods
end

target 'EcommerceTests' do
  portals_pods
end
